### ISSUE TITLE
duckduckgo command can expose IP address.

### ISSUE THREAD

**Issue by n303p4** [n303p4/kitsuchan-ng#4]
This is really bad.

**Comment by n303p4** [comment]
Due to the DuckDuckGo API's unclear limitations, the command has been shut down for now.

**Comment by LoganDark** [comment]
Why not just remove or censor the output if it contains your host IP?

For example, replace your IP with `[host IP]` or something.

**Comment by n303p4** [comment]
See rationale above. The functionality may come back in a more limited form, however.
